name: ado_downscaler
channels:
    - conda-forge
dependencies:
    - python>=3.9.7
    - esmpy==8.1.1
    - xarray==0.19.0
    - scipy==1.7.1
    - statsmodels==0.12.2
    - dask==2021.9.1
    - netCDF4==1.5.7
    - bottleneck==1.3.2
    - cfgrib==0.9.9.0
    - pip
    - pip:
        - git+https://github.com/pangeo-data/xesmf.git
