name: ado_downscaler
channels:
    - conda-forge
dependencies:
    - python>=3.5
    - esmpy==8.0.1
    - xarray==0.16.2
    - scipy==1.6.0
    - statsmodels==0.12.1
    - dask==2021.1.1
    - netCDF4==1.5.5.1
    - bottleneck==1.3.2
    - cfgrib==0.9.8.5
    - pip
    - pip:
        - git+https://github.com/pangeo-data/xesmf.git
